sudo: required
services:
  - docker

before_install:
  - docker build -t sujankota/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sujankota/react-test npm test -- --coverage

after_success:
  - docker build -t sujankota/multi-client ./client
  - docker build -t sujankota/multi-nginx ./nginx
  - docker build -t sujankota/multi-server ./server
  - docker build -t sujankota/multi-worker ./worker
  # Log in to docker CI
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" with --password-stdin
  - docker push sujankota/multi-client
  - docker push sujankota/multi-nginx
  - docker push sujankota/multi-server
  - docker push sujankota/multi-worker

