sudo: required
services:
  - docker

before_install:
  - docker build -t sujankota/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sujankota/react-test npm test -- --coverage

after_success:
  - docker build -t sujankota/multi-client ./client
  - docker build -t sujankota/multi-nginx ./nginx
  - docker build -t sujankota/multi-server ./server
  - docker build -t sujankota/multi-worker ./worker
  # Log in to docker CI
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  - docker push sujankota/multi-client
  - docker push sujankota/multi-nginx
  - docker push sujankota/multi-server
  - docker push sujankota/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-west-2-870033201739'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
